[app]
instahelper ansible_host=62.84.114.4 ansible_user=ubuntu

[prod]
prod-app ansible_host=51.250.67.107 ansible_user=ubuntu

[monitoring]
monitoring-host ansible_host=89.169.149.87 ansible_user=ubuntu

[runner]
gitlab-runner ansible_host=62.84.117.15 ansible_user=ubuntu
